In [4]:
# Auto-reload modules
# Source: https://ipython.org/ipython-doc/dev/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

# Display all of code cell's output instead of just the print statements and the last line 
# Source: https://stackoverflow.com/questions/36786722/how-to-display-full-output-in-jupyter-not-only-last-result
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Libraries

Why write code if you don't have to? Luckily, Python has many community-contributed libraries so that there's often a library that will make your life easier.

Using a library has many advantages. Here are some

1. Efficiency: Libraries provide pre-written code for common tasks, saving time and effort in development.
2. Functionality: They offer specialized functions and classes that simplify complex tasks, like data manipulation, web scraping, or machine learning.
3. Reliability: Established libraries are often well-tested and maintained by a community, reducing the risk of bugs.
4. Interoperability: Many libraries integrate seamlessly with other tools and frameworks, enhancing flexibility.
5. Community Support: Being part of a larger ecosystem means access to forums, documentation, and updates.

# Prerequisites

This notebooks uses some libraries that aren't included in Python's standard library. So make sure you install the right packages. To install the dependencies, you can use the `conda`-created `environment.yaml` that's included in the repo.

# Pandas (and a bit of SciPy and scikit-learn)

Pandas is a library that's used all over the place in the Python data handling, cleaning, processing, transformation, and analysis worlds. It integrates easily with other common libraries like NumPy, SciPy, and scikit-learn.

In [6]:
import pandas as pd  # we rename pandas to pd just to make it easier to type; this is common to see
from scipy import stats

# Load the data
agro_data = pd.read_csv("./Agrofood_co2_emission.csv")

In [53]:
# Displaying data
type(agro_data) 
agro_data.head(n=10) 
agro_data.tail() 
agro_data.shape 
agro_data.columns
agro_data.dtypes

pandas.core.frame.DataFrame

,country,year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,...,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,...,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,...,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250
5,Afghanistan,1995,14.7237,0.0557,243.8152,666.40,0.0,11.712073,54.6445,-2388.803,...,397.5498,0.0,0.0,NaN,13401971.0,3697570.0,8219467.0,8199445.0,2624.612529,0.285583
6,Afghanistan,1996,38.9302,0.2014,249.0364,686.00,0.0,11.712073,53.1637,-2388.803,...,465.2050,0.0,0.0,NaN,13952791.0,3870093.0,8569175.0,8537421.0,2838.921329,0.036583
7,Afghanistan,1997,30.9378,0.1193,276.2940,705.60,0.0,11.712073,52.0390,-2388.803,...,511.5927,0.0,0.0,NaN,14373573.0,4008032.0,8916862.0,8871958.0,3204.180115,0.415167
8,Afghanistan,1998,64.1411,0.3263,287.4346,705.60,0.0,11.712073,52.7050,-2388.803,...,541.6598,0.0,0.0,NaN,14733655.0,4130344.0,9275541.0,9217591.0,3560.716661,0.890833
9,Afghanistan,1999,46.1683,0.0895,247.4980,548.80,0.0,11.712073,35.7630,-2388.803,...,611.0611,0.0,0.0,NaN,15137497.0,4266179.0,9667811.0,9595036.0,3694.806533,1.058500

,country,year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
6960,Zimbabwe,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.0,251.1465,76500.2982,...,282.5994,0.0,0.0,417.3150,10934468.0,5215894.0,6796658.0,7656047.0,98491.026347,1.120250
6961,Zimbabwe,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.0,255.7975,76500.2982,...,255.5900,0.0,0.0,398.1644,11201138.0,5328766.0,6940631.0,7810471.0,97159.311553,0.046500
6962,Zimbabwe,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.0,327.0897,76500.2982,...,257.2735,0.0,0.0,465.7735,11465748.0,5447513.0,7086002.0,7966181.0,97668.308205,0.516333
6963,Zimbabwe,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.0,290.1893,76500.2982,...,267.5224,0.0,0.0,444.2335,11725970.0,5571525.0,7231989.0,8122618.0,98988.062799,0.985667
6964,Zimbabwe,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.0,238.7639,76500.2982,...,266.7316,0.0,0.0,444.2335,11980005.0,5700460.0,7385220.0,8284447.0,96505.221853,0.189000

(6965, 31)

Index(['country', 'year', 'Savanna fires', 'Forest fires', 'Crop Residues',
       'Rice Cultivation', 'Drained organic soils (CO2)',
       'Pesticides Manufacturing', 'Food Transport', 'Forestland',
       'Net Forest conversion', 'Food Household Consumption', 'Food Retail',
       'On-farm Electricity Use', 'Food Packaging',
       'Agrifood Systems Waste Disposal', 'Food Processing',
       'Fertilizers Manufacturing', 'IPPU', 'Manure applied to Soils',
       'Manure left on Pasture', 'Manure Management', 'Fires in organic soils',
       'Fires in humid tropical forests', 'On-farm energy use',
       'Rural population', 'Urban population', 'Total Population - Male',
       'Total Population - Female', 'total_emission',
       'Average Temperature Â°C'],
      dtype='object')

country                             object
year                                 int64
Savanna fires                      float64
Forest fires                       float64
Crop Residues                      float64
Rice Cultivation                   float64
Drained organic soils (CO2)        float64
Pesticides Manufacturing           float64
Food Transport                     float64
Forestland                         float64
Net Forest conversion              float64
Food Household Consumption         float64
Food Retail                        float64
On-farm Electricity Use            float64
Food Packaging                     float64
Agrifood Systems Waste Disposal    float64
Food Processing                    float64
Fertilizers Manufacturing          float64
IPPU                               float64
Manure applied to Soils            float64
Manure left on Pasture             float64
Manure Management                  float64
Fires in organic soils             float64
Fires in humid tropical forests    float64
On-farm energy use                 float64
Rural population                   float64
Urban population                   float64
Total Population - Male            float64
Total Population - Female          float64
total_emission                     float64
Average Temperature Â°C             float64
dtype: object

***PAUSE***: check out the [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) documentation.

In [23]:
# Getting subsets of your data
agro_data[["Area", "Year"]]
agro_data[["Area", "Year"]].iloc[4:8, :]

             Area  Year
0     Afghanistan  1990
1     Afghanistan  1991
2     Afghanistan  1992
3     Afghanistan  1993
4     Afghanistan  1994
...           ...   ...
6960     Zimbabwe  2016
6961     Zimbabwe  2017
6962     Zimbabwe  2018
6963     Zimbabwe  2019
6964     Zimbabwe  2020

[6965 rows x 2 columns]

          Area  Year
4  Afghanistan  1994
5  Afghanistan  1995
6  Afghanistan  1996
7  Afghanistan  1997

In [ ]:
agro_data["Area"].unique() # as opposed to something like set(agro_data["Area"].unique())

In [26]:
# Subsetting by "boolean mask" 
agro_data["Area"] == "Romania"
romanian_df = agro_data[agro_data["Area"] == "Romania"]
romanian_df

0       False
1       False
2       False
3       False
4       False
        ...
6960    False
6961    False
6962    False
6963    False
6964    False
Name: Area, Length: 6965, dtype: bool

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
5202,Romania,1990,6.7654,11.3361,1055.9567,312.8160,536.7635,891.0,997.8964,0.0000,...,4552.8334,0.0,0.0,6156.1269,10988961.0,12500412.0,11148927.0,11687307.0,51712.4822,1.098833
5203,Romania,1991,6.7654,11.3361,1093.4549,169.3362,536.7635,629.0,885.3348,0.0000,...,4326.8992,0.0,0.0,5086.3561,10805409.0,12648804.0,11148885.0,11693597.0,45725.1671,-0.267083
5204,Romania,1992,6.7654,11.3361,754.1263,128.5211,536.7635,485.0,990.7851,0.0000,...,3845.9871,0.0,0.0,3182.5047,10698762.0,12674596.0,11123814.0,11677149.0,44009.5120,0.485167
5205,Romania,1993,6.7654,11.3361,934.8009,94.1506,536.7635,828.0,834.2827,0.0000,...,3330.6187,0.0,0.0,2507.8915,10680466.0,12575529.0,11078754.0,11642902.0,40827.7231,-0.124583
5206,Romania,1994,6.7654,11.3361,1062.6595,36.3619,536.7635,729.0,864.4398,0.0000,...,3281.6049,0.0,0.0,1695.1024,10651531.0,12464644.0,11027789.0,11604987.0,38511.1297,1.566917
5207,Romania,1995,6.7654,11.3361,1150.5173,48.3414,535.1008,588.0,710.1278,0.0000,...,2937.4359,0.0,0.0,2079.3667,10616987.0,12348124.0,10969846.0,11563288.0,40193.0957,0.283750
5208,Romania,1996,1.9300,37.7647,816.9120,66.8909,535.1008,455.0,958.3890,0.0000,...,2991.1849,0.0,0.0,1762.4507,10577463.0,12226702.0,10903157.0,11514711.0,39891.0057,-0.363583
5209,Romania,1997,0.3713,31.3457,1221.7137,31.2502,535.1008,343.0,975.2376,0.0000,...,2992.7117,0.0,0.0,2022.5991,10532520.0,12100285.0,10829746.0,11459789.0,37624.4087,-0.314167
5210,Romania,1998,0.4232,32.5765,916.6151,13.5318,535.1008,334.0,911.6614,0.0000,...,2767.2522,0.0,0.0,1755.3027,10485543.0,11972534.0,10755933.0,11405309.0,32969.5318,0.369917
5211,Romania,1999,1.6615,31.8865,952.5527,12.2382,540.2823,222.0,774.4239,0.0000,...,2762.9296,0.0,0.0,1030.4327,10440251.0,11847806.0,10685761.0,11353246.0,30756.0598,1.053333
5212,Romania,2000,0.4588,25.1134,688.3218,10.5291,540.2823,213.0,814.2597,0.0000,...,2524.3324,0.0,0.0,954.4269,10399242.0,11728886.0,10618301.0,11301576.0,30969.0572,1.473500
5213,Romania,2001,0.8788,0.3906,1107.4472,9.0552,542.4950,168.0,924.6927,-3278.0000,...,2351.9520,0.0,0.0,643.4015,10365175.0,11618960.0,10549329.0,11248261.0,27395.4468,0.913250
5214,Romania,2002,4.7203,3.6453,851.9786,3.6456,542.4950,179.0,961.3723,-3278.0000,...,2293.1363,0.0,0.0,622.5086,10319721.0,11534955.0,10474425.0,11179107.0,26384.9954,1.368667
5215,Romania,2003,5.0636,2.0834,739.9425,0.8232,542.2777,133.0,1016.2792,-3278.0000,...,2414.3662,0.0,0.0,500.7426,10231821.0,11497098.0,10392410.0,11088909.0,28251.0834,0.430917
5216,Romania,2004,3.0238,3.7750,1324.2142,9.7138,536.9203,100.0,1065.7255,-3278.0000,...,2502.5278,0.0,0.0,554.8241,10138587.0,11452577.0,10302972.0,10986314.0,29973.9442,0.672583
5217,Romania,2005,1.6277,6.7698,1113.1890,26.6090,536.9203,76.0,968.4114,-3278.0000,...,2719.5007,0.0,0.0,508.4557,10035316.0,11395702.0,10211543.0,10880720.0,30931.6158,0.239833
5218,Romania,2006,6.5531,13.1491,922.5349,43.7707,540.2322,76.0,1011.4223,-3278.0000,...,2744.7715,0.0,0.0,628.6484,9919852.0,11324070.0,10126347.0,10783054.0,30052.6575,0.609500
5219,Romania,2007,12.9698,9.3742,537.7649,63.4099,540.0749,212.0,1098.1742,-3278.0000,...,2794.3919,0.0,0.0,511.8832,9795242.0,11240869.0,10048422.0,10695808.0,30808.5248,1.888250
5220,Romania,2008,4.3645,2.2130,983.4126,77.7493,540.0749,225.0,1214.3101,-3278.0000,...,2680.3888,0.0,0.0,632.7752,9667799.0,11153285.0,9977733.0,10619775.0,31152.5939,1.573750
5221,Romania,2009,6.0740,10.4174,869.4510,104.6326,540.9588,196.0,1212.8332,-3278.0000,...,2577.8001,0.0,0.0,939.2114,9546514.0,11071441.0,9912856.0,10553462.0,27813.7911,1.521500
5222,Romania,2010,1.4392,6.8995,946.3334,97.2395,541.5399,203.0,1166.3779,-3278.0000,...,2463.6353,0.0,0.0,959.1137,9437516.0,11002831.0,9847526.0,10487685.0,29274.5810,1.035750
5223,Romania,2011,31.1936,21.4807,1140.4554,99.3406,541.5399,205.0,1225.2294,-287048.9424,...,2210.5133,0.0,0.0,1083.6245,9342912.0,10950055.0,9791059.0,10429226.0,-252084.5804,0.734583
5224,Romania,2012,40.3275,9.7658,782.9236,88.6234,542.9014,199.0,1326.9541,-287048.9424,...,2192.2748,0.0,0.0,1293.0696,9283979.0,10887276.0,9750470.0,10386648.0,-252482.4417,1.519833
5225,Romania,2013,2.9155,6.6425,1140.7900,90.7794,541.1669,187.0,1287.9646,-287048.9424,...,2179.6872,0.0,0.0,1070.7226,9243988.0,10824213.0,9715784.0,10350762.0,-251101.8422,1.512167
5226,Romania,2014,2.8551,2.0833,1197.2834,99.7170,541.1669,172.0,1300.3835,-287048.9424,...,2181.9955,0.0,0.0,1037.3661,9207431.0,10765305.0,9681297.0,10314539.0,-250299.9577,1.651667
5227,Romania,2015,2.5980,0.0000,1101.1536,86.7653,539.4327,173.0,1323.3796,-287048.9424,...,2135.3809,0.0,0.0,1139.6933,9165608.0,10711013.0,9638704.0,10267374.0,-252449.0215,1.915667
5228,Romania,2016,0.9262,0.0000,1204.7320,73.9704,539.4327,167.0,1436.6726,-28562.1813,...,2124.9609,0.0,0.0,1189.3614,9117772.0,10660311.0,9587940.0,10209880.0,10141.2546,1.544083
5229,Romania,2017,12.4356,13.1487,1446.2339,71.5400,539.4327,174.0,1531.0597,-28562.1813,...,2057.7367,0.0,0.0,1295.9496,9065003.0,10614303.0,9540032.0,10158820.0,11420.1923,1.484500
5230,Romania,2018,1.7944,3.2546,1620.0850,64.6800,537.9181,134.0,1569.7827,-28562.1813,...,1905.6290,0.0,0.0,1544.2440,9007536.0,10573098.0,9493519.0,10113264.0,11811.6455,2.024917
5231,Romania,2019,15.1020,10.2832,1582.9773,58.2512,551.8901,145.0,1637.9486,-28562.1813,...,1886.3526,0.0,0.0,1497.0300,8946041.0,10537319.0,9450890.0,10073321.0,10138.6347,2.499083
5232,Romania,2020,9.7308,9.3745,1073.8501,47.0400,551.8901,139.0,1618.9444,-28562.1813,...,1872.8094,0.0,0.0,1497.0300,8880997.0,10507365.0,9405845.0,10036193.0,11853.6347,2.309583

In [38]:
# Creating new columns and doing math with columns
romanian_df["total_fires"] = romanian_df["Savanna fires"] + romanian_df["Forest fires"]
romanian_df[["Savanna fires", "Forest fires", "total_fires"]].biloc[:3]

/var/folders/wt/l509j2v13614w84pwcgyhw9w0000gp/T/ipykernel_41534/1972565496.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  romanian_df["total_fires"] = romanian_df["Savanna fires"] + romanian_df["Forest fires"]

      Savanna fires  Forest fires  total_fires
5202         6.7654       11.3361      18.1015
5203         6.7654       11.3361      18.1015
5204         6.7654       11.3361      18.1015

## Exercise 1 - by yourself or in groups

1. Create a dataframe from `agro_data` with the columns "Manure applied to Soils", "Manure left on Pasture", and "Manure Management" with only the rows that correspond to Canada
2. What is the mean (using a DataFrame method) of each of those three columns?

## Exercise 2 - together

Say you want to combine the agricultural data and GDP data so you can look at things how GDP varies with different columns in the agricultural data. Let's figure out how to combine the datasets by joining on the country and year.

In [44]:
gdp_data = pd.read_csv("gdp.csv")
gdp_data.head(2)

        Entity Code  Year  GDP (constant 2015 US$)
0  Afghanistan  AFG  2002               7228796000
1  Afghanistan  AFG  2003               7867263500

In [51]:
gdp_data.rename(columns={"Entity": "country", "GDP (constant 2015 US$)": "gdp", "Year": "year"}, inplace=True)
agro_data.rename(columns={"Area": "country", "GDP (constant 2015 US$)": "gdp", "Year": "year"}, inplace=True)
gdp_data.head(2)
agro_data.head(2)

       country Code  year         gdp
0  Afghanistan  AFG  2002  7228796000
1  Afghanistan  AFG  2003  7867263500

,country,year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667

Pandas has a method for merging dataframes: [pd.merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html).

In [52]:
pd.merge(gdp_data, agro_data, how="inner", on=["year", "country"])

,country,Code,year,gdp,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature Â°C
0,Afghanistan,AFG,2002,7228796000,9.0562,0.0000,266.1975,529.2000,0.0,11.712073,...,592.5613,0.0,0.0,NaN,17086910.0,4893013.0,10562202.0,10438055.0,6035.816468,1.084167
1,Afghanistan,AFG,2003,7867263500,55.8052,0.0000,324.2195,568.4000,0.0,11.712073,...,603.1024,0.0,0.0,NaN,17909063.0,5155788.0,11397483.0,11247647.0,6449.089231,0.679333
2,Afghanistan,AFG,2004,7978515500,11.9759,0.0000,266.9995,764.4000,0.0,11.712073,...,576.0374,0.0,0.0,NaN,18692107.0,5426872.0,11862726.0,11690825.0,6734.998231,1.398833
3,Afghanistan,AFG,2005,8874481000,5.3259,0.0000,383.7498,627.2000,0.0,11.983047,...,604.7668,0.0,0.0,NaN,19378962.0,5691836.0,12302104.0,12109086.0,7001.297527,0.457333
4,Afghanistan,AFG,2006,9349922000,4.4081,0.0000,333.6093,627.2000,0.0,12.931389,...,626.2428,0.0,0.0,NaN,19961972.0,5931478.0,12828447.0,12614497.0,7076.181947,1.477333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5286,Zimbabwe,ZWE,2016,20142980000,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,...,282.5994,0.0,0.0,417.3150,10934468.0,5215894.0,6796658.0,7656047.0,98491.026347,1.120250
5287,Zimbabwe,ZWE,2017,20964866000,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,...,255.5900,0.0,0.0,398.1644,11201138.0,5328766.0,6940631.0,7810471.0,97159.311553,0.046500
5288,Zimbabwe,ZWE,2018,22015179000,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,...,257.2735,0.0,0.0,465.7735,11465748.0,5447513.0,7086002.0,7966181.0,97668.308205,0.516333
5289,Zimbabwe,ZWE,2019,20621079000,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,...,267.5224,0.0,0.0,444.2335,11725970.0,5571525.0,7231989.0,8122618.0,98988.062799,0.985667
5290,Zimbabwe,ZWE,2020,19009139000,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,...,266.7316,0.0,0.0,444.2335,11980005.0,5700460.0,7385220.0,8284447.0,96505.221853,0.189000

## Exercise 3 - by yourself or in groups

Is there a statistical (p < 0.05) difference between the average temperatures in Argentina and in Mexico from 2000-present? 

For this we can use the [SciPy](https://scipy.org/) library which "provides algorithms for optimization, integration, interpolation, eigenvalue problems, algebraic equations, differential equations, statistics and many other classes of problems."

You can use [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html#ttest-ind) to test whether the averages are different. You can use [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html#normaltest) to test whether a sample is normally distributed.

In [72]:
# To get you started...
argentina_temps = agro_data[(agro_data["Area"] == "Argentina") & (agro_data["Year"] >= 2000)]["Average Temperature Â°C"]
mexico_temps = agro_data[(agro_data["Area"] == "Mexico") & (agro_data["Year"] >= 2000)]["Average Temperature Â°C"]

## Exercise 4 - by yourself or in groups

The [Iris dataset](https://scikit-learn.org/1.5/auto_examples/datasets/plot_iris_dataset.html) is a dataset consisting of measurements of the sepal length and width and pedal lengh and width of three different types of irises. It's often used as an example dataset in "intro to machine learning using Pandas"-type tutorials. The library [scikit-learn](https://scikit-learn.org/stable/) is standard ML library in Python. The Iris dataset is loaded from the scikit-learn library in the code cell below. Do the following:

1. Create a dataframe that has five columns: (1) sepal length, (2) sepal width, (3) pedal length, (4) pedal width, (5) column for the indicator column that indicates which type of iris a given row corresponds to. If we think about the dataset from the perspective of "predict the type of Iris from the sepal and pedal measurements" than the sepal and pedal measurements are called the ***predictors*** (a.k.a. independent variables) and the 5th, indicator column is called the ***response*** (a.k.a. depedent variable). 
2. Replace the four measurement columns with their "[z-score](https://en.wikipedia.org/wiki/Standard_score)" where you subtract the mean and divide by the standard deviation.
3. Save your new dataframe from (2) as a semicolon (";") separated file without the index (hint: use `pd.DataFrame.to_csv(sep=";", index=False)`)
4. Start exploring some of scikit-learn's ML functionalities via the Iris dataset. Here are some examples of things you could do:
    - Perform [PCA](https://scikit-learn.org/dev/modules/generated/sklearn.decomposition.PCA.html) on the predictors and see if the three iris species are well separated in the lower dimensional subspace of the first 2 or 3 PCA components. 
    - Explore different classifiers (e.g., [k-nearest neighbors](https://scikit-learn.org/dev/modules/generated/sklearn.neighbors.KNeighborsClassifier.html), [support-vector machines](https://scikit-learn.org/1.5/modules/svm.html)) that predict iris species from the sepal and pedal measurement predictors. You could compare different classifiers' performances via [cross-validation](https://scikit-learn.org/stable/modules/cross_validation.html).

In [58]:
from sklearn import datasets

iris = datasets.load_iris()
iris_data = pd.DataFrame(data=iris["data"]

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

## References

- To visualize how pandas transforms data: [here](https://pandastutor.com/vis.html)

## Potential additional topics

- `pd.Series`
- `.apply`
- Saving data
-